version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-mcp
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

  postgres-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-mcp-app
    restart: unless-stopped
    ports:
      - "8432:8432"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      MCP_MODE: http
      MCP_PORT: 8432
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  postgres_data: 