version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSL=prefer
      - MCP_MODE=http
      - MCP_PORT=8432
      - MCP_LOG_LEVEL=info
      - MCP_LOG_SQL=true
    ports:
      - "8432:8432"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  pgdata: 